MODEL_NAME: deeplabv3plus_resnet101
NUM_CLASSES: 19
OUTPUT_SRTIDE: 16
PATH_TO_PTH: /home/usrs/taniuchi/workspace/projects/coloring_ir/DeepLabV3Plus_Pytorch/checkpoints/best_deeplabv3plus_resnet101_cityscapes_os16.pth
batch_size: 32
color_mean: !!python/tuple
- 0.232
- 0.267
- 0.233
color_std: !!python/tuple
- 0.173
- 0.173
- 0.172
gpu_id: 0
n_layers: 100
num_epochs: 100
optimizer:
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
path_cpt: checkpoints/deeplabv3plus_resnet101_202505121926
path_logs: logs/deeplabv3plus_resnet101_202505121926
rootpath: /home/usrs/taniuchi/workspace/datasets/ir_seg_dataset
